apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: luisa-parra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:latest
        command:
          - /bin/bash
          - -c
          - "apt-get update && apt-get install -y telnet && sleep 3600"
